version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on: 
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - "8080:80"
      
volumes:
  gem_cache:
  db_data:
  node_modules: